name:                src-mini-egison
version:             0.1.0.0
license:             MIT

dependencies:
- base >= 4.7 && < 5
- mini-egison

library:
  source-dirs: src

executables:
  complete:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - src-mini-egison
    - mini-egison
